# Generated by Django 5.1.1 on 2024-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Apellido y Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo eléctronico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_contacto', models.IntegerField(choices=[(0, 'consulta'), (1, 'reclamo'), (2, 'sugerencia'), (3, 'felicitaciones')], verbose_name='Tipo de contacto')),
                ('suscripcion', models.BooleanField(default=False, verbose_name='Suscribirme a correos informativos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
